apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: agricloud
spec:
  type: NodePort
  selector:
    app: agricloud-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

